#!/bin/sh

set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)"
HELPER="$ROOT/openwrt-squid-profile-ui/files/usr/libexec/squid-profiles"
UCI_DEFAULTS="$ROOT/openwrt-squid-profile-ui/files/etc/uci-defaults/90_squid_profiles"
INITD="$ROOT/openwrt-squid-profile-ui/files/etc/init.d/squid-profiles"
COMPOSE="$ROOT/test/compose.yml"

fail() { printf 'FAIL: %s\n' "$*" >&2; exit 1; }

for script in "$HELPER" "$UCI_DEFAULTS" "$INITD"; do
	[ -f "$script" ] || fail "missing script: $script"
	sh -n "$script" || fail "shell syntax failed: $script"
done

grep -q 'unique_backup_path' "$HELPER" || fail "helper does not define unique backup handling"
grep -q 'backup_current_config' "$HELPER" || fail "helper does not back up before apply"
grep -q 'Backed up current Squid configuration before modification' "$HELPER" || fail "helper does not report per-apply backup path"
grep -q 'squid -k parse' "$HELPER" || fail "helper does not run squid -k parse"
grep -q 'squid -f "$SQUID_CONF" -k reconfigure' "$HELPER" || fail "helper does not reconfigure Squid"
grep -q 'squid -f "$SQUID_CONF"' "$HELPER" || fail "helper does not start Squid when not running"
grep -q 'access_log none' "$HELPER" || fail "helper should avoid tmp access log writes"
grep -q 'Generated by luci-app-squid-profiles' "$HELPER" || fail "helper does not write managed skeleton marker"
grep -q 'write_mime_conf' "$HELPER" || fail "helper does not create Squid MIME table"
if grep -q 'pinger_enable' "$HELPER"; then fail "helper should not emit pinger_enable on OpenWrt Squid"; fi

grep -q 'luci-app-squid-profiles.json:/usr/share/luci/menu.d/luci-app-squid-profiles.json' "$COMPOSE" || fail "compose does not mount LuCI menu file"
grep -q 'squid_profiles.lua:/usr/lib/lua/luci/controller/squid_profiles.lua' "$COMPOSE" || fail "compose does not mount LuCI controller"
grep -q 'view/squid-profiles:/www/luci-static/resources/view/squid-profiles' "$COMPOSE" || fail "compose does not mount LuCI view directory"
grep -q 'squid-profiles:/etc/init.d/squid-profiles' "$COMPOSE" || fail "compose does not mount plugin init script"
grep -q './runtime/etc-squid:/etc/squid' "$COMPOSE" || fail "compose does not mount Squid runtime tree"

printf 'shell static checks passed\n'
