#!/bin/sh

set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)"
HELPER="$ROOT/openwrt-squid-profile-ui/files/usr/libexec/squid-profiles"
UCI_DEFAULTS="$ROOT/openwrt-squid-profile-ui/files/etc/uci-defaults/90_squid_profiles"
INITD="$ROOT/openwrt-squid-profile-ui/files/etc/init.d/squid-profiles"
WORKFLOW="$ROOT/.github/workflows/openwrt-package.yml"
COMPOSE="$ROOT/test/compose.yml"

fail() { printf 'FAIL: %s\n' "$*" >&2; exit 1; }

for script in "$HELPER" "$UCI_DEFAULTS" "$INITD"; do
	[ -f "$script" ] || fail "missing script: $script"
	sh -n "$script" || fail "shell syntax failed: $script"
done

[ -f "$WORKFLOW" ] || fail "missing GitHub Actions workflow"
[ -d "$ROOT/openwrt-squid-profile-ui/files" ] || fail "missing package source tree"
[ ! -e "$ROOT/packages/luci-app-squid-profiles" ] || fail "ambiguous duplicate package path exists under packages/"

grep -q 'unique_backup_path' "$HELPER" || fail "helper does not define unique backup handling"
grep -q 'backup_current_config' "$HELPER" || fail "helper does not back up before apply"
grep -q 'Backed up current Squid configuration before modification' "$HELPER" || fail "helper does not report per-apply backup path"
grep -q 'squid -k parse' "$HELPER" || fail "helper does not run squid -k parse"
grep -q 'squid -f "$SQUID_CONF" -k reconfigure' "$HELPER" || fail "helper does not reconfigure Squid"
grep -q 'squid -f "$SQUID_CONF"' "$HELPER" || fail "helper does not start Squid when not running"
grep -q 'access_log none' "$HELPER" || fail "helper should avoid tmp access log writes"
grep -q 'Generated by luci-app-squid-profiles' "$HELPER" || fail "helper does not write managed skeleton marker"
grep -q 'write_mime_conf' "$HELPER" || fail "helper does not create Squid MIME table"
grep -q 'collect_profile_domains' "$HELPER" || fail "helper does not support exclusive profile modes"
grep -F -q 'normalize_domain' "$HELPER" || fail "helper does not normalize Squid wildcard syntax"
grep -F -q 'case "$1" in ""|*"/"*|*" "*|*".."*|*.) return 1 ;; esac' "$HELPER" || fail "helper does not enforce basic domain syntax"
if grep -q 'pinger_enable' "$HELPER"; then fail "helper should not emit pinger_enable on OpenWrt Squid"; fi

grep -q 'luci-app-squid-profiles.json:/usr/share/luci/menu.d/luci-app-squid-profiles.json' "$COMPOSE" || fail "compose does not mount LuCI menu file"
grep -q 'squid_profiles.lua:/usr/lib/lua/luci/controller/squid_profiles.lua' "$COMPOSE" || fail "compose does not mount LuCI controller"
grep -q 'view/squid-profiles:/www/luci-static/resources/view/squid-profiles' "$COMPOSE" || fail "compose does not mount LuCI view directory"
grep -q 'squid-profiles:/etc/init.d/squid-profiles' "$COMPOSE" || fail "compose does not mount plugin init script"
grep -q './runtime/etc-squid:/etc/squid' "$COMPOSE" || fail "compose does not mount Squid runtime tree"
grep -q './runtime/config:/etc/config' "$COMPOSE" || fail "compose does not mount OpenWrt config runtime tree"

grep -q 'openwrt/sdk:mediatek-mt7622-main' "$WORKFLOW" || fail "workflow does not default to OpenWrt SDK Docker image"
grep -q 'docker run --rm' "$WORKFLOW" || fail "workflow does not use OpenWrt SDK Docker container"
grep -q 'chmod 0777 sdk-bin' "$WORKFLOW" || fail "workflow does not make /builder/bin bind mount writable"
grep -q 'cp -a /work/openwrt-squid-profile-ui' "$WORKFLOW" || fail "workflow does not copy the single package source into SDK"
grep -q './setup.sh' "$WORKFLOW" || fail "workflow does not initialize SDK container"
grep -q 'make "package/${PACKAGE_NAME}/compile" V=s' "$WORKFLOW" || fail "workflow does not compile package"
grep -q 'make package/index V=s' "$WORKFLOW" || fail "workflow does not generate package index"
grep -q '*.apk' "$WORKFLOW" || fail "workflow does not collect APK artifacts"
if grep -F -q '*.ipk' "$WORKFLOW"; then fail "workflow should not collect legacy package artifacts"; fi

printf 'shell static checks passed\n'
