#!/bin/sh

set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)"
HELPER="$ROOT/openwrt-squid-profile-ui/files/usr/libexec/squid-profiles"
UCI_DEFAULTS="$ROOT/openwrt-squid-profile-ui/files/etc/uci-defaults/90_squid_profiles"
INITD="$ROOT/openwrt-squid-profile-ui/files/etc/init.d/squid-profiles"
COMPOSE="$ROOT/test/compose.yml"

fail() {
	printf 'FAIL: %s\n' "$*" >&2
	exit 1
}

for script in "$HELPER" "$UCI_DEFAULTS" "$INITD"; do
	[ -f "$script" ] || fail "missing script: $script"
	sh -n "$script" || fail "shell syntax failed: $script"
done

grep -q 'unique_backup_path' "$HELPER" || fail "helper does not define unique backup handling"
grep -q 'squid -k parse' "$HELPER" || fail "helper does not run squid -k parse"
grep -q 'squid -k reconfigure' "$HELPER" || fail "helper does not reconfigure Squid"
grep -q 'Generated by luci-app-squid-profiles' "$HELPER" || fail "helper does not write managed skeleton marker"

grep -q '../openwrt-squid-profile-ui/files/usr/share/luci:/usr/share/luci' "$COMPOSE" || fail "compose does not mount LuCI tree"
grep -q '../openwrt-squid-profile-ui/files/etc/init.d:/etc/init.d' "$COMPOSE" || fail "compose does not mount init.d tree"
grep -q './runtime/etc-squid:/etc/squid' "$COMPOSE" || fail "compose does not mount Squid runtime tree"

printf 'shell static checks passed\n'
