#!/bin/sh /etc/rc.common

START=19
USE_PROCD=1

HELPER="/usr/libexec/squid-profiles"

start_service() {
	[ -x "$HELPER" ] && "$HELPER" init
}

reload_service() {
	[ -x "$HELPER" ] && "$HELPER" apply
}

boot() {
	start_service
}
