#!/bin/sh

set -eu

HELPER="/usr/libexec/squid-profiles"

if [ ! -x "$HELPER" ]; then
	echo "squid-profiles helper is missing: $HELPER" >&2
	exit 1
fi

"$HELPER" init

if ! uci show squid_profiles >/dev/null 2>&1; then
	uci batch <<'EOUCI'
set squid_profiles.core=globals
set squid_profiles.core.enabled='1'
add squid_profiles network
set squid_profiles.@network[-1].cidr='192.168.1.0/24'
set squid_profiles.@network[-1].vlan='LAN'
set squid_profiles.@network[-1].description='Default LAN'
add squid_profiles profile
set squid_profiles.@profile[-1].name='default'
set squid_profiles.@profile[-1].description='Default profile'
commit squid_profiles
EOUCI
fi

exit 0
